filename: "mocks.go"
pkgname: "mocks"
packages:
  github.com/ngoctrng/bookz/internal/account/usecases:
    config:
      dir: "internal/account/mocks"
    interfaces:
      Repository:
      Usecase:
  github.com/ngoctrng/bookz/internal/book/usecases:
    config:
      dir: "internal/book/mocks"
    interfaces:
      Repository:
      Usecase:
  github.com/ngoctrng/bookz/internal/exchange/usecases:
    config:
      dir: "internal/exchange/mocks"
    interfaces:
      Repository:
      Usecase:
      MessageBus:
