development:
  dialect: postgresql
  datasource: host=localhost port=5432 dbname=bookz user=postgres password=123456
  dir: pkg/migration/migrations
  table: gorp_migrations

test:
  dialect: postgresql
  datasource: host=localhost port=5432 dbname=bookz user=postgres password=123456
  dir: pkg/migration/migrations
  table: gorp_migrations