// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ngoctrng/bookz/internal/book"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) Delete(id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id int)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(id int) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(id int) (*book.BookInfo, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *book.BookInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*book.BookInfo, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *book.BookInfo); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*book.BookInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepository_Expecter) FindByID(id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(id int)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(bookInfo *book.BookInfo, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(bookInfo, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(id int) (*book.BookInfo, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBy provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBy(ids []int) ([]*book.Book, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetBy")
	}

	var r0 []*book.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) ([]*book.Book, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) []*book.Book); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*book.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBy'
type MockRepository_GetBy_Call struct {
	*mock.Call
}

// GetBy is a helper method to define mock.On call
//   - ids []int
func (_e *MockRepository_Expecter) GetBy(ids interface{}) *MockRepository_GetBy_Call {
	return &MockRepository_GetBy_Call{Call: _e.mock.On("GetBy", ids)}
}

func (_c *MockRepository_GetBy_Call) Run(run func(ids []int)) *MockRepository_GetBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetBy_Call) Return(books []*book.Book, err error) *MockRepository_GetBy_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockRepository_GetBy_Call) RunAndReturn(run func(ids []int) ([]*book.Book, error)) *MockRepository_GetBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetProposal provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProposal(pid int) *book.ProposalDetails {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for GetProposal")
	}

	var r0 *book.ProposalDetails
	if returnFunc, ok := ret.Get(0).(func(int) *book.ProposalDetails); ok {
		r0 = returnFunc(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*book.ProposalDetails)
		}
	}
	return r0
}

// MockRepository_GetProposal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProposal'
type MockRepository_GetProposal_Call struct {
	*mock.Call
}

// GetProposal is a helper method to define mock.On call
//   - pid int
func (_e *MockRepository_Expecter) GetProposal(pid interface{}) *MockRepository_GetProposal_Call {
	return &MockRepository_GetProposal_Call{Call: _e.mock.On("GetProposal", pid)}
}

func (_c *MockRepository_GetProposal_Call) Run(run func(pid int)) *MockRepository_GetProposal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetProposal_Call) Return(proposalDetails *book.ProposalDetails) *MockRepository_GetProposal_Call {
	_c.Call.Return(proposalDetails)
	return _c
}

func (_c *MockRepository_GetProposal_Call) RunAndReturn(run func(pid int) *book.ProposalDetails) *MockRepository_GetProposal_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List() ([]*book.BookInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*book.BookInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*book.BookInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*book.BookInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*book.BookInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockRepository_Expecter) List() *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockRepository_List_Call) Run(run func()) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(bookInfos []*book.BookInfo, err error) *MockRepository_List_Call {
	_c.Call.Return(bookInfos, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func() ([]*book.BookInfo, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(b *book.Book) error {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*book.Book) error); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - b *book.Book
func (_e *MockRepository_Expecter) Save(b interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", b)}
}

func (_c *MockRepository_Save_Call) Run(run func(b *book.Book)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *book.Book
		if args[0] != nil {
			arg0 = args[0].(*book.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(b *book.Book) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(b *book.Book) error {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*book.Book) error); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - b *book.Book
func (_e *MockRepository_Expecter) Update(b interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", b)}
}

func (_c *MockRepository_Update_Call) Run(run func(b *book.Book)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *book.Book
		if args[0] != nil {
			arg0 = args[0].(*book.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(b *book.Book) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository) Upsert(books []*book.Book) error {
	ret := _mock.Called(books)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*book.Book) error); ok {
		r0 = returnFunc(books)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - books []*book.Book
func (_e *MockRepository_Expecter) Upsert(books interface{}) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", books)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(books []*book.Book)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*book.Book
		if args[0] != nil {
			arg0 = args[0].([]*book.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(err error) *MockRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(books []*book.Book) error) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Create(b *book.Book) error {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*book.Book) error); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - b *book.Book
func (_e *MockUsecase_Expecter) Create(b interface{}) *MockUsecase_Create_Call {
	return &MockUsecase_Create_Call{Call: _e.mock.On("Create", b)}
}

func (_c *MockUsecase_Create_Call) Run(run func(b *book.Book)) *MockUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *book.Book
		if args[0] != nil {
			arg0 = args[0].(*book.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsecase_Create_Call) Return(err error) *MockUsecase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_Create_Call) RunAndReturn(run func(b *book.Book) error) *MockUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Delete(id int, ownerID string) error {
	ret := _mock.Called(id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(id, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
//   - ownerID string
func (_e *MockUsecase_Expecter) Delete(id interface{}, ownerID interface{}) *MockUsecase_Delete_Call {
	return &MockUsecase_Delete_Call{Call: _e.mock.On("Delete", id, ownerID)}
}

func (_c *MockUsecase_Delete_Call) Run(run func(id int, ownerID string)) *MockUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_Delete_Call) Return(err error) *MockUsecase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_Delete_Call) RunAndReturn(run func(id int, ownerID string) error) *MockUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FulfillProposal provides a mock function for the type MockUsecase
func (_mock *MockUsecase) FulfillProposal(pid int) error {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for FulfillProposal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(pid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_FulfillProposal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FulfillProposal'
type MockUsecase_FulfillProposal_Call struct {
	*mock.Call
}

// FulfillProposal is a helper method to define mock.On call
//   - pid int
func (_e *MockUsecase_Expecter) FulfillProposal(pid interface{}) *MockUsecase_FulfillProposal_Call {
	return &MockUsecase_FulfillProposal_Call{Call: _e.mock.On("FulfillProposal", pid)}
}

func (_c *MockUsecase_FulfillProposal_Call) Run(run func(pid int)) *MockUsecase_FulfillProposal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsecase_FulfillProposal_Call) Return(err error) *MockUsecase_FulfillProposal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_FulfillProposal_Call) RunAndReturn(run func(pid int) error) *MockUsecase_FulfillProposal_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Get(id int) (*book.BookInfo, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *book.BookInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*book.BookInfo, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *book.BookInfo); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*book.BookInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id int
func (_e *MockUsecase_Expecter) Get(id interface{}) *MockUsecase_Get_Call {
	return &MockUsecase_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockUsecase_Get_Call) Run(run func(id int)) *MockUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsecase_Get_Call) Return(bookInfo *book.BookInfo, err error) *MockUsecase_Get_Call {
	_c.Call.Return(bookInfo, err)
	return _c
}

func (_c *MockUsecase_Get_Call) RunAndReturn(run func(id int) (*book.BookInfo, error)) *MockUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUsecase
func (_mock *MockUsecase) List() ([]*book.BookInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*book.BookInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*book.BookInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*book.BookInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*book.BookInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockUsecase_Expecter) List() *MockUsecase_List_Call {
	return &MockUsecase_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockUsecase_List_Call) Run(run func()) *MockUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUsecase_List_Call) Return(bookInfos []*book.BookInfo, err error) *MockUsecase_List_Call {
	_c.Call.Return(bookInfos, err)
	return _c
}

func (_c *MockUsecase_List_Call) RunAndReturn(run func() ([]*book.BookInfo, error)) *MockUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Update(b *book.Book, ownerID string) error {
	ret := _mock.Called(b, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*book.Book, string) error); ok {
		r0 = returnFunc(b, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - b *book.Book
//   - ownerID string
func (_e *MockUsecase_Expecter) Update(b interface{}, ownerID interface{}) *MockUsecase_Update_Call {
	return &MockUsecase_Update_Call{Call: _e.mock.On("Update", b, ownerID)}
}

func (_c *MockUsecase_Update_Call) Run(run func(b *book.Book, ownerID string)) *MockUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *book.Book
		if args[0] != nil {
			arg0 = args[0].(*book.Book)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_Update_Call) Return(err error) *MockUsecase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_Update_Call) RunAndReturn(run func(b *book.Book, ownerID string) error) *MockUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}
